### ISSUE TITLE
Move pokemongo.json file to a seperate repository

### ISSUE THREAD

**Issue by BrunnerLivio** [celandro/pokebattler-fight#8]
Is it possible to move the pokemongo.json, and everything whats needed to fetch the data for it to a seperate repository? 

The benefits are from it:

- Easier to find the latest Pokemongo GAME_MASTER file using google
- Better version control
- Cleaner project
- When I have a project, which needs the latest GAME_MASTER file, I don't want to depend on a "pokebattler-fight" repository, because it actually does not have anything to do with my project

I hope you understand, what I'm trying to say :)

**Comment by sp00x** [comment]
It would be good with an archive of older versions also, as the legacy moves are not visible in the always-latest-version

**Comment by celandro** [comment]
I can move it to a java repo that will have all the compiled protos, the binary gamemaster and the json gamemaster when I have some free time. My biggest issue is I can no longer get the binary game master file out of the android cache directory so I am dependent on others to update

**Comment by hacknug** [comment]
I uploaded the last one two days ago. I don't think there's a new one but in case there is, I can reupload it too. https://gist.github.com/hacknug/924b0a61b7404deceb17e04d3409910f

**Comment by BrunnerLivio** [comment]
@sp00x good idea!
@celandro I think as soon as projects depend on it, someone is going to constantly update the GAME MASTER file. And as it has [shown on reddit](https://www.reddit.com/r/pokemongodev/comments/5wfv8k/github_repository_with_always_uptodate_game/), it is some interest around this topic. I don't think this will be an issue

Are we going to create a Github organisation or does anyone want to maintain the repository on their account?

And before we are going to create a repository; how are we going to structure it? 
My suggestion is:

```
├── bin
│   └── update_gamemaster.sh
└── versions
    ├── 0.57.1
    │   ├── GAME_MASTER.json
    │   └── GAME_MASTER.protobuf
    ├── 0.57.2
    │   ├── GAME_MASTER.json
    │   └── GAME_MASTER.protobuf
    └── latest
        ├── GAME_MASTER.json
        └── GAME_MASTER.protobuf
```

**Comment by BrunnerLivio** [comment]
I created [a repository](https://github.com/BrunnerLivio/pokemongo-game-master). I can move it to an organisation later, if you want to. I added @hacknug protobuf file and  @celandro json file. Thanks for that!

Happy if you contribute in any way to the repository!

**Comment by celandro** [comment]
That repo needs to have the json generator added as a script. Probably need another repository that provides the compiled Java classes of the protos as well. I may have time this weekend to work on it
